### ISSUE TITLE
Dynamically set ergo node version or grab latest release

### ISSUE THREAD

**Issue by TheStophe** [jkrek17/Ergo#2]
In the `.env` there's ERGO_VERSION which I set to 5.0.24, and incurred an error. 

However it seems the docker file has 5.0.23 hard coded in. Maybe make this default to 5.0.23 but dynamically set based off the .env file?

https://github.com/jkrek17/Ergo/blob/9558f5f1f7d6b56eb8281ae6850f99145bcde245/ergo-node-docker/Dockerfile#L5

**Comment by jkrek17** [comment]
I overlooked that detail. It should be set in the .env file now and carry through the rest of the scripts.
